name: .NET Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 🔍 Restore dependencies
        run: dotnet restore src/UnitTests/UnitTests.csproj

      - name: 🛠 Build tests
        run: dotnet build src/UnitTests/UnitTests.csproj --configuration Release --no-restore

      - name: 🧪 Run tests
        run: dotnet test src/UnitTests/UnitTests.csproj --no-build --verbosity normal
